plugins {
    id 'java-library'
}

dependencies {
    implementation project(':common')
    compileOnly 'org.spongepowered:mixin:0.8.5'
    compileOnly 'net.fabricmc:fabric-loader:0.15.11'
    compileOnly fileTree(dir: 'libs', include: ['*.jar'])
}

jar {
    archiveBaseName = 'Titanium-mc26.2'
    from {
        project(':common').sourceSets.main.output
    }
}
